
# SEO settings
title: amaechler
description: "Sticky Notes To Myself"
url: https://amaechler.com
# baseurl: "/"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-103141150-1

repo: github.com/amaechler/amaechler.github.io

# Build settings
permalink   : /:year/:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

paginate: 4
paginate_path: "/page/:num/"

source: src
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: :expanded

# Author settings
author:
  name     : Andreas Maechler
  job      : Software Developer
  bio      : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  email    : amaechler.github.io@gmail.com
  url      : https://amaechler.com
  github   : https://github.com/amaechler
  twitter  : https://twitter.com/amaechler
  linkedin : https://linkedin.com/in/andreasmaechler

# social settings
og_locale: "en_CA"
twitter_card: "summary_large_image"
twitter_site: "@amaechler"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - src
  - CNAME
